### ISSUE TITLE
missing diff & CurSearch highlights 

### ISSUE THREAD

**Issue by gegoune** [nyoom-engineering/oxocarbon.nvim#27]
Hello, seems like oxocarbon.nvim does not set up any highlighting groups for diffs. This results in ugly (default) highlights in various plugins like neogit and diffview. 

Also, `CurSearch` highlight is used for highlighting search result under the cursor - at the moment such search result gets no highlight at all. It could be as simple as linking it to `IncSearch`.

Could you please add those as well?

**Comment by shaunsingh** [comment]
Sure!

**Comment by shaunsingh** [comment]
Added support for diff highlights, forgot about CurSearch. I'll add it
