### ISSUE TITLE
[Feature? request] Oxocarbon Alacritty

### ISSUE THREAD

**Issue by richardhttps** [nyoom-engineering/oxocarbon.nvim#28]
Apologies if this is not the right place for this.
Been using oxocarbon for a week now and loving it.
It would great to have oxocarbon for the terminal too. Any possible plans for that?

I wish I could help with this but I have zero clue how themes are done.

**Comment by shaunsingh** [comment]
The theme itself is written in base 16 (https://github.com/shaunsingh/nix-darwin-dotfiles/blob/main/modules/themes/base16-carbon-dark.yaml), so you can use it across multiple applications. I personally do this in my dotfiles (https://github.com/shaunsingh/nix-darwin-dotfiles/blob/6f6969028e10fc8afa7b504453c6eb086e6c5b83/modules/home.nix#L313) but I'll definitely make it into its own thing soon

**Comment by saccarosium** [comment]
@richardhttps now there is an [official port](https://github.com/nyoom-engineering/oxocarbon-alacritty) for alacritty

**Comment by ryouiki-tenkai** [comment]
thank you @saccarosium
