### ISSUE TITLE
Bug: oxocarbon can only be set as color scheme once

### ISSUE THREAD

**Issue by chrisgrieser** [nyoom-engineering/oxocarbon.nvim#38]
To reproduce:
1. remove everything that sets a `colorscheme` from your neovim config
2. run `:colorscheme oxocarbon`
3. run `:colorscheme blue` (or any other colorscheme)
4. run `:colorscheme oxocarbon` again

The first two `colorscheme` will work, but setting `oxocarbon` as colorscheme a *second* time does not work. This is relevant for some use cases where you want to change your colorscheme during runtime, for example [styler](https://github.com/folke/styler.nvim) or [auto-dark-mode](https://github.com/f-person/auto-dark-mode.nvim).

I checked, oxocarbon seems to be the only theme that has this issue, other themes, builtin or from the community, do not have this problem.

**Comment by cvigilv** [comment]
I second this, find attached a gif showcasing the problem
![Peek 2022-12-18 15-23](https://user-images.githubusercontent.com/30091515/208303630-4a76feb3-6a1e-4f34-b56a-6753f496a2d4.gif)

**Comment by ethanmsl** [comment]
same,  no issues with other default or added colorschemes
**nvim v0.8.1**
**macOS**

nothing coming up from `:checkhealth`

**Comment by boydkelly** [comment]
Thinking this is the same issue.  my startup theme is set to nightfly, and although oxocarbon is loaded as shown below with Lazy.nvim, I can't switch to it at all.   

Running L  ● oxocarbon.nvim 0.39ms  start
~                    dir    /var/home/bkelly/.local/share/nvim/lazy/oxocarbon.nvim
~                    url    https://github.com/nyoom-engineering/oxocarbon.nvim
~                    branch main
~                    commit e5038beazy but showing loaded at start,  but oxocarbon theme not available.

running neovim nightly `neovim-0.9.0~dev.557.g94ce25065-500.fc37.x86_64`
