### ISSUE TITLE
FR: Add styling for markdown

### ISSUE THREAD

**Issue by chrisgrieser** [nyoom-engineering/oxocarbon.nvim#39]
Right now, markdown documents are almost entirely colored with the default color, which is a bit of a bummer

**Comment by shaunsingh** [comment]
I believe this should be fixed now, feel free to reopen if you have any issues

**Comment by Velnbur** [comment]
Got problems with links and text wrapped with backticks. With conceal feature enabled they are looking the same with normal text (white and plain)
