### ISSUE TITLE
color isn't applied to all jsx tags

### ISSUE THREAD

**Issue by datsfilipe** [nyoom-engineering/oxocarbon.nvim#46]
Only applying the colors to custom components (like "Section") and not for normal tags (like "div"):
*Obs: I don't know if it's a bug report or a feature request.*
![image](https://user-images.githubusercontent.com/76636791/216822908-f24d0889-3e41-45e6-9838-76f413c7525d.png)
Also, white for props/attributes doesn't seems right.

**Comment by theVerySharpFlat** [comment]
@datsfilipe this should be fixed now!

**Comment by datsfilipe** [comment]
Looks awesome now, thanks!
