### ISSUE TITLE
Statusline?

### ISSUE THREAD

**Issue by pwnwriter** [nyoom-engineering/oxocarbon.nvim#55]
Hey, I kinda liked the statusline used in the screenshots... Is it possible to get that statusline configuration

img: 

![](https://0x0.st/Hzz2.png)

**Comment by shaunsingh** [comment]
Sorry for not seeing this earlier, the statusline is from `nyoom.nvim`, you can find it under `fnl/modules/ui/modeline/config.fnl`, I may move it into its own plugin the future
