### ISSUE TITLE
warning at startup when setup{} empty param

### ISSUE THREAD

**Issue by lost22git** [nyoom-engineering/oxocarbon.nvim#75]
my config used lazy.nvim
```lua
local M = {
  "nyoom-engineering/oxocarbon.nvim",
  lazy = false,
  priority = 1000,
  enabled = function() return vim.g.theme == 'oxocarbon' end,
}

function M.config()
  require('oxocarbon').setup {
  }
  vim.cmd [[ colorscheme 'oxocarbon' ]]
end

return M
```

![Screenshot 2023-06-20 224713](https://github.com/nyoom-engineering/oxocarbon.nvim/assets/65008815/e2a0df33-bb00-41d4-b53f-c380438b8f73)

**Comment by shaunsingh** [comment]
no need to call setup, just `vim.cmd [[ colorscheme 'oxocarbon' ]]` does the trick
https://github.com/nyoom-engineering/oxocarbon.nvim#usage

**Comment by lost22git** [comment]
It doesn't seem to work for me

![Screenshot 2023-06-21 031722](https://github.com/nyoom-engineering/oxocarbon.nvim/assets/65008815/f43a7270-fe98-46f6-a21b-26ab66dbdfba)

**Comment by shaunsingh** [comment]
What version of neovim do you have?

**Comment by lost22git** [comment]
```
branch main
commit 12a7507
```

**Comment by lost22git** [comment]
NVIM v0.9.1
